### ISSUE TITLE
Extension Audit Report (Desktop version)

### ISSUE THREAD

**Issue by ghost** [ObliviousParadigm/Extensions#31]
[issues.pdf](https://github.com/ObliviousParadigm/Extensions/files/4292927/issues.pdf). Performance analysis for desktop versions. Mobile version untested.
Ignore Performance metrics here.
High priority: Screen readers and PWA
SEO isn't important as of yet.

**Comment by ObliviousParadigm** [comment]
Woah! This is really cool! Thank you! I will look into Screen Readers.
